In [31]:
import pandas as pd
import numpy as np
import openpyxl

In [65]:
key = pd.read_excel("hasil\Data_Laporan_2024_Audit.xlsx", sheet_name="gen_info")["kode entitas"]

gen_info = pd.read_excel("hasil\Data_Laporan_2024_Audit.xlsx", sheet_name="gen_info")
gen_info = gen_info.set_index("kode entitas")
gen_info

,nama entitas,penjelasan perubahan nama dari akhir periode laporan sebelumnya,nomor identifikasi entitas,industri utama entitas,standar akutansi yang dipilih,sektor,subsektor,industri,subindustri,informasi pemegang saham pengendali,...,jumlah hal audit utama,paragraf hal audit utama,tanggal laporan audit atau hasil laporan review,auditor tahun berjalan,nama partner audit tahun berjalan,lama tahun penugasan partner yang menandatangani,auditor tahun sebelumnya,nama partner audit tahun sebelumnya,kepatuhan terhadap pemenuhan peraturan ojk nomor: 75/pojk.04/2017 tentang tanggung jawab direksi atas laporan keuangan,kepatuhan terhadap pemenuhan independensi akuntan yang memberikan jasa audit di pasar modal sesuai dengan pojk nomor 13/pojk.03/2017 tentang penggunaan jasa akuntan publik dalam kegiatan jasa keuangan
kode entitas,,,,,,,,,,,,,,,,,,,,,
AALI,Astra Agro Lestari Tbk,NaN,AA298,Umum / General,PSAK,D. Consumer Non-Cyclicals,D2. Food & Beverage,D23. Agricultural Products,D232. Plantations & Crops,National Corporation,...,1.0,"Hal audit utama adalah hal-hal yang, menurut p...",2025-02-20,"Rintis, Jumadi, Rianto dan Rekan","Eddy Rintis, S.E., CPA",4,"KAP Tanudiredja, Wibisana, Rintis dan Rekan","Eddy Rintis, S.E., CPA",Ya / Yes,Ya / Yes
ABBA,Mahaka Media Tbk,NaN,AA384,Umum / General,PSAK,E. Consumer Cyclicals,E6. Media & Entertainment,E61. Media,E614. Consumer Publishing,National Corporation,...,1.0,Penjelasan atas hal audit utama: Perusahaan me...,2025-03-25,"KAP Antadaya, Helmiansyah Dan Yassirli",Helmiansyah Irawan,2,"KAP Antadaya, Helmiansyah Dan Yassirli",Helmiansyah Irawan,Ya / Yes,Ya / Yes
ABDA,Asuransi Bina Dana Arta Tbk,NaN,AA030,Asuransi / Insurance,PSAK,G. Financials,G4. Insurance,G41. Insurance,G412. General Insurance,Foreign Corporation,...,2.0,Liabilitas kontrak asuransi jangka panjang dan...,2025-02-28,"KAP Purwantono, Sungkoro dan Surja",Ignatius Yokajaya,2,"KAP Purwantono, Sungkoro dan Surja",Ignatius Yokajaya,Ya / Yes,Ya / Yes
ABMM,ABM Investama Tbk,NaN,AA600,Umum / General,PSAK,A. Energy,"A1. Oil, Gas & Coal",A12. Coal,A121. Coal Production,National Corporation,...,1.0,Pengakuan Pendapatan/Revenue Recognition,2025-03-11,"KAP Purwantono, Sungkoro dan Surja",Benyanto Suherman,1,"KAP Purwantono, Sungkoro dan Surja",Chang Hartono,Ya / Yes,Ya / Yes
ACES,PT Aspirasi Hidup Indonesia Tbk,NaN,AA492,Umum / General,PSAK,E. Consumer Cyclicals,E7. Retailing,E74. Specialty Retail,E743. Home Improvement Retail,National Corporation,...,1.0,Aset Hak Guna dan Liabilitas Sewa,2025-03-26,"KAP Amir Abadi Jusuf, Aryanto, Mawar Rekan",Eishennoraz,NaN,"KAP Amir Abadi Jusuf, Aryanto, Mawar Rekan",Eishennoraz,Ya / Yes,Ya / Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YULE,Yulie Sekuritas Indonesia Tbk,NaN,AA450,Sekuritas / Securities,PSAK,G. Financials,G3. Investment Service,G31. Investment Services,G312. Investment Banking & Brokerage Services,Individual WNI,...,NaN,NaN,2025-03-26,KAP Jojo Sunarjo Rekan,Muhamad Idris,4,KAP Jojo Sunarjo Rekan,Muhamad Idris,Ya / Yes,Ya / Yes
ZATA,PT Bersama Zatta Jaya Tbk,NaN,AB134,Umum / General,PSAK,E. Consumer Cyclicals,E7. Retailing,E74. Specialty Retail,E741. Apparel & Textile Retail,National Corporation,...,2.0,Uang Muka sewa dan Renovasi dan Piutang Non-Us...,2025-03-27,"KAP Jamaludin, Ardi, Sukimto dan Rekan",Raynold Nainggolan,2,"KAP Jamaludin, Ardi, Sukimto dan Rekan",Raynold Nainggolan,Ya / Yes,Ya / Yes
ZINC,PT Kapuas Prima Coal Tbk,NaN,AA784,Umum / General,PSAK,B. Basic Materials,B1. Basic Materials,B14. Metals & Minerals,B146. Diversified Metals & Minerals,National Corporation,...,NaN,NaN,2025-03-27,KAP Mirawati Sensi Idris,"Juninho Widjaja, CPA",NaN,KAP Mirawati Sensi Idris,"Juninho Widjaja, CPA",Ya / Yes,Ya / Yes
ZONE,PT Mega Perintis Tbk.,NaN,AA868,Umum / General,PSAK,E. Consumer Cyclicals,E7. Retailing,E74. Specialty Retail,E741. Apparel & Textile Retail,Individual WNI,...,2.0,Sewa sesuai dengan PSAK 73 sewa penilaian pers...,2025-03-28,"Teramihardja, Pradhono Chandra","Teramihardja, Pradhono Chandra",NaN,"KAP Teramihardja, Pradhono Chandra",Andri Rinaldi,Ya / Yes,Ya / Yes
ZYRX,PT Zyrexindo Mandiri Buana Tbk,NaN,AB026,Umum / General,PSAK,I. Technology,I2. Technology Hardware & Equipment,I22. Computer Hardware,I221. Computer Hardware,Individual WNI,...,NaN,"Hal audit utama adalah hal-hal yang, menurutpe...",2025-03-25,KAP Johannes Juara Rekan,"Hari Manurung, CPA",3,KAP Johannes Juara Rekan,"Hari Manurung, CPA",Ya / Yes,Ya / Yes

In [79]:
ringkasan_saham = pd.read_excel("Ringkasan Saham.xlsx").drop("No", axis=1)
ringkasan_saham = ringkasan_saham.rename(columns= {"Kode Saham":"kode entitas"})
ringkasan_saham = ringkasan_saham.set_index("kode entitas")
ringkasan_saham

,Nama Perusahaan,Remarks,Sebelumnya,Open Price,Tanggal Perdagangan Terakhir,First Trade,Tertinggi,Terendah,Penutupan,Selisih,...,Bid,Bid Volume,Listed Shares,Tradeble Shares,Weight For Index,Foreign Sell,Foreign Buy,Non Regular Volume,Non Regular Value,Non Regular Frequency
kode entitas,,,,,,,,,,,,,,,,,,,,,
AADI,Adaro Andalan Indonesia Tbk.,--MO1130000000A121------------,7075,7125,24 Apr 2025,7125,7275,7025,7050,-25,...,7050,400,7786891760,7786891760,1928813089,880100,1330500,183,1116300,1
AALI,Astra Agro Lestari Tbk.,--MO113E000200D232------------,5750,5775,24 Apr 2025,5775,5875,5775,5800,50,...,5800,61900,1924688333,1924688333,390711732,61200,146000,0,0,0
ABBA,Mahaka Media Tbk.,--U-4100000000E614-E---------X,23,0,24 Apr 2025,0,24,22,24,1,...,24,4257300,3935892857,3935892857,1298844643,700000,0,0,0,0
ABDA,Asuransi Bina Dana Arta Tbk.,--U-4105000000G412-----------X,3400,0,24 Apr 2025,0,0,0,3400,0,...,0,0,620806680,620806680,81325675,0,0,0,0,0
ABMM,ABM Investama Tbk.,--MO1105000000A121------------,3300,3320,24 Apr 2025,3320,3430,3310,3360,60,...,3350,100000,2753165000,2753165000,418205764,440200,225700,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZATA,Bersama Zatta Jaya Tbk.,--U-4130000000E741-----------X,8,0,24 Apr 2025,0,8,7,7,-1,...,7,4200,8496000000,1700000000,2046686400,0,0,0,0,0
ZBRA,Dosni Roha Indonesia Tbk.,--UO2130000000C311M--L--------,50,50,24 Apr 2025,50,50,50,50,0,...,0,0,2510706263,2510706263,501639111,0,0,0,0,0
ZINC,Kapuas Prima Coal Tbk.,--U-4100000000B146--D--------X,13,0,24 Apr 2025,0,13,13,13,0,...,13,127300,25250000000,25250000000,8733975000,0,0,0,0,0
ZONE,Mega Perintis Tbk.,--UO2130000000E741------------,805,0,24 Apr 2025,0,815,800,815,10,...,805,300,870171478,870171478,132527116,0,0,0,0,0
ZYRX,Zyrexindo Mandiri Buana Tbk.,--UO2130000000I221------------,114,114,24 Apr 2025,114,116,111,116,2,...,115,200,1333334556,1333334556,269200247,0,0,0,0,0

In [62]:
daftar_saham = pd.read_excel("Daftar Saham.xlsx", sheet_name="Sheet1")
daftar_saham.columns = ["no","kode entitas","nama entitas","ipo","jumlah saham","papan pencatatan"]
daftar_saham = daftar_saham.drop("no", axis=1).set_index("kode entitas")
daftar_saham

,nama entitas,ipo,jumlah saham,papan pencatatan
kode entitas,,,,
AALI,Astra Agro Lestari Tbk.,09 Des 1997,1.924.688.333,Utama
ABBA,Mahaka Media Tbk.,03 Apr 2002,3.935.892.857,Pemantauan Khusus
ABDA,Asuransi Bina Dana Arta Tbk.,06 Jul 1989,620.806.680,Pemantauan Khusus
ABMM,ABM Investama Tbk.,06 Des 2011,2.753.165.000,Utama
ACES,Aspirasi Hidup Indonesia Tbk.,06 Nov 2007,17.120.389.700,Utama
...,...,...,...,...
KKES,Kusuma Kemindo Sentosa Tbk.,08 Agt 2022,1.500.000.000,Pemantauan Khusus
ELPI,Pelayaran Nasional Ekalya Purn,08 Agt 2022,7.412.000.000,Utama
EURO,Estee Gold Feet Tbk.,08 Agt 2022,2.548.826.428,Akselerasi
KLIN,Klinko Karya Imaji Tbk.,09 Agt 2022,1.307.530.330,Akselerasi
TOOL,Rohartindo Nusantara Luas Tbk.,09 Agt 2022,2.050.020.320,Pengembangan

In [ ]:
main_df = pd.DataFrame({
    "kode entitas": [],
    "nama entitas": [],
    "sektor": [],
    "subsektor": [],
    "currency": [],
    "value currency": [],
    "satuan": [],
    "value satuan" : [],
    "auditor": [],
    "ipo": [],
    "jumlah saham": [],
    "% publik": [],
    "saham publik": [],
    "market cap in mio": [],
    "now": [],
    "target": [],
    "safety": [],
    "per": [],
    "ey": [],
    "peru": [],
    "bv": [],
    "pbv": [],
    "pbvx": [],
    "cfps": [],
    "tobins'q": [],
    "ev ebitda": [],
    "asset": [],
    "liabilits": [],
    "ekuitas": [],
    "income yoy": [],
    "income qoq": [],
    "profit": [],
    "ocf yoy": [],
    "roe": [],
    "roa": [],
    "current ratio": [],
    "cash ratio": [],
    "der": [],
    "tie": [],
    "npm": [],
    "gpm": [],
    "dividen": [],
    "dy": [],
    "ocf": [],
    "icf": [],
    "fcf": [],
    "laba rugi": [],
    "dar": [],
    "likuiditas": [],
    "underwriting": [],
    "kecukupan dana": [],
    "premi yoy": [],
    "beban klaim": [],
    "retensi": []
})

main_df["kode entitas"] = key
main_df = main_df.set_index("kode entitas")
main_df

,nama entitas,sektor,subsektor,currency,value currency,satuan,value satuan,auditor,ipo,jumlah saham,...,icf,fcf,laba rugi,dar,likuiditas,underwriting,kecukupan dana,premi yoy,beban klaim,retensi
kode entitas,,,,,,,,,,,,,,,,,,,,,
AALI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABBA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABDA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABMM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ACES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YULE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZINC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZYRX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
main_df.update(daftar_saham)

C:\Users\ae\AppData\Local\Temp\ipykernel_18512\2292234349.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['Astra Agro Lestari Tbk.' 'Mahaka Media Tbk.'
 'Asuransi Bina Dana Arta Tbk.' 'ABM Investama Tbk.'
 'Aspirasi Hidup Indonesia Tbk.' 'Samcro Hyosung Adilestari Tbk.'
 'Acset Indonusa Tbk.' 'Adhi Commuter Properti Tbk.'
 'Akasha Wira International Tbk.' 'Adhi Karya (Persero) Tbk.'
 'Adira Dinamika Multi Finance T' 'Polychem Indonesia Tbk'
 'Adaro Minerals Indonesia Tbk.' 'Alamtri Resources Indonesia Tb'
 'Anugerah Spareparts Sejahtera ' 'Asia Sejahtera Mina Tbk.'
 'Bank Raya Indonesia Tbk.' 'Bank IBK Indonesia Tbk.'
 'Asuransi Harta Aman Pratama Tb' 'FKS Food Sejahtera Tbk.'
 'Argha Karya Prima Industry Tbk' 'AKR Corporindo Tbk.'
 'Mineral Sumberdaya Mandiri Tbk' 'Alkindo Naratama Tbk.'
 'Ancara Logistics Indonesia Tbk' 'Alakasa Industrindo Tbk'
 'Alumindo Light Metal Industry ' 'Asuransi Multi Artha Guna Tbk.'
 'Makmur Berkah Amanda Tbk.' 'Bank Amar Indonesia Tbk.'
 'Asahimas Flat Glass Tbk.' 'Amman Mineral Internasional Tb'
 'Sumber Alfaria Trijaya Tbk.' 'Andira Agro Tbk.'
 'Austindo Nusantara Jaya Tbk.' 'Apexindo Pratama Duta Tbk.'
 'Arita Prima Indonesia Tbk.' 'Asiaplast Industries Tbk.'
 'Agung Podomoro Land Tbk.' 'Archi Indonesia Tbk.' 'Atlas Resources Tbk.'
 'Arkora Hydro Tbk.' 'Arthavest Tbk' 'Asuransi Bintang Tbk.'
 'Asuransi Dayin Mitra Tbk.' 'Astra Graphia Tbk.'
 'Astra International Tbk.' 'Autopedia Sukses Lestari Tbk.'
 'Asuransi Maximus Graha Persada' 'Andalan Sakti Primaindo Tbk.'
 'Alam Sutera Realty Tbk.' 'Asuransi Ramayana Tbk.'
 'Adi Sarana Armada Tbk.' 'Trimitra Prawara Goldland Tbk.'
 'Anabatic Technologies Tbk.' 'Atlantis Subsea Indonesia Tbk.'
 'Astra Otoparts Tbk.' 'Avia Avian Tbk.' 'Era Digital Media Tbk.'
 'Tera Data Indonusa Tbk.' 'Janu Putra Sejahtera Tbk.'
 'Agro Yasa Lestari Tbk.' 'Bank MNC Internasional Tbk.'
 'Bank Capital Indonesia Tbk.' 'Bersama Mencapai Puncak Tbk.'
 'Saranacentral Bajatama Tbk.' 'Bali Towerindo Sentra Tbk.'
 'Bekasi Asri Pemula Tbk.' 'Benteng Api Technic Tbk.'
 'Mitra Angkasa Sejahtera Tbk.' 'Bayu Buana Tbk' 'Bank Central Asia Tbk.'
 'Allo Bank Indonesia Tbk.' 'Bank KB Bukopin Tbk.' 'Buana Finance Tbk.'
 'Bank Mestika Dharma Tbk.' 'Bank Negara Indonesia (Persero'
 'Bank Rakyat Indonesia (Persero' 'Pelayaran Nasional Bina Buana '
 'Krom Bank Indonesia Tbk.' 'Bank Tabungan Negara (Persero)'
 'Bank Neo Commerce Tbk.' 'MNC Kapital Indonesia Tbk.'
 'Bank JTrust Indonesia Tbk.' 'Bumi Citra Permai Tbk.'
 'Berdikari Pondasi Perkasa Tbk.' 'Bank Danamon Indonesia Tbk.'
 'Estika Tata Tiara Tbk.' 'Jobubu Jarum Minahasa Tbk.'
 'Bank Pembangunan Daerah Banten' 'Trisula Textile Industries Tbk'
 'Bekasi Fajar Industrial Estate' 'BFI Finance  Indonesia Tbk.'
 'Bank Ganesha Tbk.' 'Bhakti Multi Artha Tbk.' 'MNC Asia Holding Tbk.'
 'Primarindo Asia Infrastructure' 'Perma Plasindo Tbk.'
 'Bhuwanatala Indah Permai Tbk.' 'Blue Bird Tbk.'
 'BISI International Tbk.' 'Bank Pembangunan Daerah Jawa B'
 'Bank Pembangunan Daerah Jawa T' 'Bukit Darmo Property Tbk'
 'Bank QNB Indonesia Tbk.' 'Superior Prima Sukses Tbk.'
 'Berlian Laju Tanker Tbk' 'Graha Layar Prima Tbk.'
 'Berkah Prima Perkasa Tbk.' 'Bank Maspion Indonesia Tbk.'
 'Lavender Bina Cendikia Tbk.' 'Bundamedik Tbk.'
 'Bank Mandiri (Persero) Tbk.' 'Bintang Mitra Semestaraya Tbk'
 'Global Mediacom Tbk.' 'Bank Bumi Arta Tbk.' 'Bank CIMB Niaga Tbk.'
 'Bank Maybank Indonesia Tbk.' 'Bank Permata Tbk.'
 'Newport Marine Services Tbk.' 'Bintang Oto Global Tbk.'
 'Bali Bintang Sejahtera Tbk.' 'Garuda Metalindo Tbk.'
 'Batavia Prosperindo Internasio' 'Batavia Prosperindo Trans Tbk.'
 'Indo Kordsa Tbk.' 'Barito Renewables Energy Tbk.'
 'Bank Syariah Indonesia Tbk.' 'Bumi Resources Minerals Tbk.'
 'Berlina Tbk.' 'Raja Roti Cemerlang Tbk.' 'Bumi Serpong Damai Tbk.'
 'Bank Sinarmas Tbk.' 'Bintang Samudera Mandiri Lines'
 'Baramulti Suksessarana Tbk.' 'Bank Of India Indonesia Tbk.'
 'Bumi Teknokultura Unggul Tbk' 'Bank SMBC Indonesia Tbk.'
 'Bank BTPN Syariah Tbk.' 'Segar Kumala Indonesia Tbk.'
 'Budi Starch & Sweetener Tbk.' 'Bukalapak.com Tbk.'
 'Bukaka Teknik Utama Tbk.' 'Bumi Resources Tbk.'
 'Bukit Uluwatu Villa Tbk.' 'Bank Victoria International Tb'
 'Eagle High Plantations Tbk.' 'Bayan Resources Tbk.'
 'Cahayaputra Asa Keramik Tbk.' 'Campina Ice Cream Industry Tbk'
 'Metro Healthcare Indonesia Tbk' 'Industri dan Perdagangan Bintr'
 'Capital Financial Indonesia Tb' 'Cashlez Worldwide Indonesia Tb'
 'Cardig Aero Services Tbk.' 'Bangun Kosambi Sukses Tbk.'
 'Citra Buana Prasida Tbk.' 'Cakra Buana Resources Energi T'
 'Citra Borneo Utama Tbk.' 'Communication Cable Systems In'
 'Centratama Telekomunikasi Indo' 'Clipan Finance Indonesia Tbk.'
 'Citra Nusantara Gemilang Tbk.' 'Chemstar Indonesia Tbk.'
 'Pelita Teknologi Global Tbk.' 'Chitose Internasional Tbk.'
 'Cita Mineral Investindo Tbk.' 'Sariguna Primatirta Tbk.'
 'Colorpak Indonesia Tbk.' 'Cemindo Gemilang Tbk.'
 'AirAsia Indonesia Tbk.' 'Cisarua Mountain Dairy Tbk.'
 'Nusantara Sejahtera Raya Tbk.' 'Wahana Interfood Nusantara Tbk'
 'Charoen Pokphand Indonesia Tbk' 'Central Proteina Prima Tbk.'
 'Toba Surimi Industries Tbk.' 'Carsurin Tbk.'
 'Catur Sentosa Adiprana Tbk.' 'Cahayasakti Investindo Sukses '
 'Cipta Selera Murni Tbk.' 'Cisadane Sawit Raya Tbk.' 'Citra Tubindo Tbk.'
 'Ciputra Development Tbk.' 'Citatah Tbk.' 'Petrindo Jaya Kreasi Tbk.'
 'ITSEC Asia Tbk.' 'Daaz Bara Lestari Tbk.' 'Remala Abadi Tbk.'
 'Duta Intidaya Tbk.' 'Caturkarda Depo Bangunan Tbk.' 'Darma Henwa Tbk'
 'Dewi Shri Farmindo Tbk.' 'Dafam Property Indonesia Tbk.'
 'Diagnos Laboratorium Utama Tbk' 'Delta Giri Wacana Tbk.'
 'Arkadia Digital Media Tbk.' 'Distribusi Voucher Nusantara T'
 'Central Omega Resources Tbk.' 'Puradelta Lestari Tbk.'
 'Digital Mediatama Maxima Tbk.' 'Diamond Food Indonesia Tbk.'
 'Bank Oke Indonesia Tbk.' 'Indoritel Makmur Internasional'
 'BUMA Internasional Grup Tbk.' 'Era Media Sejahtera Tbk.'
 'Global Sukses Digital Tbk.' 'Duta Pertiwi Nusantara Tbk.'
 'Dua Putra Utama Makmur Tbk.' 'Dharma Polimetal Tbk.'
 'Dharma Samudera Fishing Indust' 'Dharma Satya Nusantara Tbk.'
 'Dian Swastatika Sentosa Tbk' 'Duta Pertiwi Tbk'
 'Darya-Varia Laboratoria Tbk.' 'Dwi Guna Laksana Tbk.'
 'Dyandra Media International Tb' 'Eastparc Hotel Tbk.'
 'Electronic City Indonesia Tbk.' 'Indointernet Tbk.'
 'Ekadharma International Tbk.' 'Data Sinergitama Jaya Tbk.'
 'Pelayaran Nasional Ekalya Purn' 'Elnusa Tbk.'
 'Bakrieland Development Tbk.' 'Megapolitan Developments Tbk.'
 'Champ Resto Indonesia Tbk.' 'Energi Mega Persada Tbk.'
 'Morenzo Abadi Perkasa Tbk.' 'Megalestari Epack Sentosaraya '
 'Enseval Putera Megatrading Tbk' 'Erajaya Swasembada Tbk.'
 'Sinar Eka Selaras Tbk.' 'Eratex Djaja Tbk.'
 'Sinergi Inti Plastindo Tbk.' 'ESSA Industries Indonesia Tbk.'
 'Esta Multi Usaha Tbk.' 'Ever Shine Tex Tbk.' 'Estee Gold Feet Tbk.'
 'XLSMART Telecom Sejahtera Tbk.' 'FAP Agri Tbk.'
 'Fajar Surya Wisesa Tbk.' 'MD Entertainment Tbk.' 'Fimperkasa Utama Tbk.'
 'Hotel Fitra International Tbk.' 'Falmaco Nonwoven Industri Tbk.'
 'Fortune Mate Indonesia Tbk' 'Multi Garam Utama Tbk.'
 'Sentra Food Indonesia Tbk.' 'Fortune Indonesia Tbk'
 'Lotte Chemical Titan Tbk.' nan 'Fuji Finance Indonesia Tbk.'
 'Futura Energi Global Tbk.' 'Wijaya Cahaya Timber Tbk.'
 'Gunawan Dianjaya Steel Tbk.' 'Goodyear Indonesia Tbk.'
 'Gema Grahasarana Tbk.' 'Golden Energy Mines Tbk.' 'Gudang Garam Tbk.'
 'Gunung Raja Paksi Tbk.' 'Gihon Telekomunikasi Indonesia'
 'Garuda Indonesia (Persero) Tbk' 'Gajah Tunggal Tbk.'
 'Globe Kita Terang Tbk.' 'Galva Technologies Tbk.'
 'Garuda Maintenance Facility Ae' 'Gowa Makassar Tourism Developm'
 'Visi Telekomunikasi Infrastruk' 'Intra Golflink Resorts Tbk.'
 'Garudafood Putra Putri Jaya Tb' 'GoTo Gojek Tokopedia Tbk.'
 'Perdana Gapuraprima Tbk.' 'Geoprima Solusi Tbk.'
 'Ingria Pratama Capitalindo Tbk' 'Griptha Putra Persada Tbk.'
 'Graha Prima Mentari Tbk.' 'Equity Development Investment '
 'Garda Tujuh Buana Tbk' 'Grahaprima Suksesmandiri Tbk.'
 'GTS Internasional Tbk.' 'Aman Agrindo Tbk.' 'Gunanusa Eramandiri Tbk.'
 'Greenwood Sejahtera Tbk.' 'Gozco Plantations Tbk.'
 'Himalaya Energi Perkasa Tbk.' 'Hasnur Internasional Shipping '
 'Arsy Buana Travelindo Tbk.' 'Haloni Jane Tbk.'
 'Habco Trans Maritima Tbk.' 'Minahasa Membangun Hebat Tbk.'
 'Radana Bhaskara Finance Tbk.' 'Hensel Davest Indonesia Tbk.'
 'Panasia Indo Resources Tbk.' 'Medikaloka Hermina Tbk.'
 'Jaya Trishindo Tbk.' 'DFI Retail Nusantara Tbk.' 'Hillcon Tbk.'
 'H.M. Sampoerna Tbk.' 'Buyung Poetra Sembada Tbk.'
 'Harapan Duta Pertiwi Tbk.' 'Menteng Heritage Realty Tbk.'
 'Hartadinata Abadi Tbk.' 'Harum Energy Tbk.'
 'Humpuss Maritim Internasional ' 'Ecocare Indo Pasifik Tbk.'
 'MNC Energy Investments Tbk.' 'Intan Baru Prana Tbk.'
 'Indo Boga Sukses Tbk.' 'Inti Bangun Sejahtera Tbk.'
 'Indofood CBP Sukses Makmur Tbk' 'Idea Indonesia Akademi Tbk.'
 'Indonesia Pondasi Raya Tbk.' 'Indonesia Fibreboard Industry '
 'Champion Pacific Indonesia Tbk' 'Era Mandiri Cemerlang Tbk.'
 'Ikapharmindo Putramas Tbk.' 'Indomobil Multi Jasa Tbk.'
 'Impack Pratama Industri Tbk.' 'Indal Aluminium Industry Tbk.'
 'Indo Komoditi Korpora Tbk.' 'Vale Indonesia Tbk.'
 'Indofood Sukses Makmur Tbk.' 'Royalindo Investa Wijaya Tbk.'
 'Indo-Rama Synthetics Tbk.' 'Indospring Tbk.' 'Tanah Laut Tbk'
 'Indika Energy Tbk.' 'Sinergi Inti Andalan Prima Tbk'
 'Indah Kiat Pulp & Paper Tbk.' 'Inocycle Technology Group Tbk.'
 'Bank Artha Graha Internasional' 'Indonesian Paradise Property T'
 'Indah Prakasa Sentosa Tbk.' 'Toba Pulp Lestari Tbk.'
 'Intraco Penta Tbk.' 'Inter Delta Tbk' 'Indocement Tunggal Prakarsa Tb'
 'Sumber Sinergi Makmur Tbk.' 'Era Graharealty Tbk.'
 'Indonesia Kendaraan Terminal T' 'Jasa Armada Indonesia Tbk.'
 'Indopoly Swakarsa Industry Tbk' 'MNC Vision Networks Tbk.'
 'Itama Ranoraya Tbk.' 'Aviana Sinar Abadi Tbk.'
 'Isra Presisi Indonesia Tbk.' 'Indosat Tbk.'
 'Indo American Seafoods Tbk.' 'Steel Pipe Industry of Indones'
 'Indonesian Tobacco Tbk.' 'Indo Tambangraya Megah Tbk.'
 'Jhonlin Agro Raya Tbk.' 'Jasnita Telekomindo Tbk.'
 'Jaya Agra Wattie Tbk.' 'Armada Berjaya Trans Tbk.'
 'Jembo Cable Company Tbk.' 'Graha Andrasentra Propertindo '
 'Jakarta International Hotels &' 'Jaya Konstruksi Manggala Prata'
 'Jakarta Kyoei Steel Works Tbk.' 'Japfa Comfeed Indonesia Tbk.'
 'Jaya Real Property Tbk.' 'Jasa Marga (Persero) Tbk.'
 'Jakarta Setiabudi Internasiona' 'Jasuindo Tiga Perkasa Tbk.'
 'KMI Wire & Cable Tbk.' 'Kabelindo Murni Tbk.' 'First Media Tbk.'
 'Kedawung Setia Industrial Tbk.' 'Kencana Energi Lestari Tbk.'
 'Mulia Boga Raya Tbk.' 'Ketrosden Triasmitra Tbk.'
 'Keramika Indonesia Assosiasi T' 'Kedaung Indah Can Tbk'
 'Kawasan Industri Jababeka Tbk.' 'Hoffmen Cleanindo Tbk.'
 'Kino Indonesia Tbk.' 'Kioson Komersial Indonesia Tbk'
 'Kusuma Kemindo Sentosa Tbk.' 'Resource Alam Indonesia Tbk.'
 'Pelayaran Kurnia Lautan Semest' 'Kalbe Farma Tbk.'
 'Klinko Karya Imaji Tbk.' 'Kurniamitra Duta Sentosa Tbk.'
 'Kobexindo Tractors Tbk.' 'Kokoh Exa Nusantara Tbk.'
 'Kokoh Inti Arebama Tbk' 'DMS Propertindo Tbk.' 'MNC Land Tbk.'
 'Bangun Karya Perkasa Jaya Tbk.' 'Kentanix Supra International T'
 'Green Power Group Tbk.' 'UBC Medical Indonesia Tbk.'
 'Leyand International Tbk.' 'LCK Global Kedaton Tbk.'
 'Logindo Samudramakmur Tbk.' 'Imago Mulia Persada Tbk.'
 'MSIG Life Insurance Indonesia ' 'Link Net Tbk.' 'Lion Metal Works Tbk.'
 'Homeco Victoria Makmur Tbk.' 'Lupromax Pelumas Indonesia Tbk'
 'Lionmesh Prima Tbk.' 'Logisticsplus International Tb'
 'Lippo General Insurance Tbk.' 'Multi Prima Sejahtera Tbk'
 'Lippo Karawaci Tbk.' 'Star Pacific Tbk' 'Matahari Department Store Tbk.'
 'Lenox Pasifik Investama Tbk.' 'Eka Sari Lorena Transport Tbk.'
 'PP London Sumatra Indonesia Tb' 'Lautan Luas Tbk.'
 'Lima Dua Lima Tiga Tbk.' 'Mandiri Herindo Adiperkasa Tbk'
 'Malindo Feedmill Tbk.' 'Manggung Polahraya Tbk.'
 'Map Aktif Adiperkasa Tbk.' 'MAP Boga Adiperkasa Tbk.'
 'Mitra Adiperkasa Tbk.' 'Mark Dynamics Indonesia Tbk.'
 'Multistrada Arah Sarana Tbk.' 'Bank Multiarta Sentosa Tbk.'
 'Maxindo Karya Anugerah Tbk.' 'Merdeka Battery Materials Tbk.'
 'Martina Berto Tbk.' 'M Cash Integrasi Tbk.' 'Prima Andalan Mandiri Tbk.'
 'Bank China Construction Bank I' 'Modernland Realty Tbk.'
 'Medco Energi Internasional Tbk' 'Hetzer Medical Indonesia Tbk.'
 'Harta Djaya Karya Tbk.' 'Menn Teknologi Indonesia Tbk.' 'Merck Tbk.'
 'Mandala Multifinance Tbk.' 'Multifiling Mitra Indonesia Tb'
 'Magna Investama Mandiri Tbk.' 'Mahkota Group Tbk.'
 'Multi Hanna Kreasindo Tbk.' 'Multi Indocitra Tbk.'
 'Midi Utama Indonesia Tbk.' 'Mitra Keluarga Karyasehat Tbk.'
 'Sanurhasta Mitra Tbk.' 'Sinar Terang Mandiri Tbk.'
 'Mitra International Resources ' 'Mitra Investindo Tbk.'
 'Multikarya Asia Pasifik Raya T' 'Metropolitan Kentjana Tbk.'
 'Menthobi Karyatama Raya Tbk.' 'Multi Bintang Indonesia Tbk.'
 'Mulia Industrindo Tbk' 'Multipolar Tbk.' 'Multipolar Technology Tbk.'
 'Multi Medika Internasional Tbk' 'Mega Manunggal Property Tbk.'
 'Media Nusantara Citra Tbk.' 'Madusari Murni Indah Tbk.'
 'Mora Telematika Indonesia Tbk.' 'Mitra Pedagang Indonesia Tbk.'
 'Mitra Pinasthika Mustika Tbk.' 'Megapower Makmur Tbk.'
 'Matahari Putra Prima Tbk.' 'Maha Properti Indonesia Tbk.'
 'MPX Logistics International Tb' 'Maskapai Reasuransi Indonesia '
 'Multisarana Intan Eduka Tbk.' 'MNC Digital Entertainment Tbk.'
 'Multi Spunindo Jaya Tbk.' 'MNC Sky Vision Tbk.'
 'Metrodata Electronics Tbk.' 'Dayamitra Telekomunikasi Tbk.'
 'Metropolitan Land Tbk.' 'Murni Sadar Tbk.' 'Meta Epsi Tbk.'
 'Metro Realty Tbk.' 'Malacca Trust Wuwungan Insuran'
 'Mutuagung Lestari Tbk.' 'Mayora Indah Tbk.'
 'Asia Pacific Investama Tbk.' 'Adiwarna Anugerah Abadi Tbk.'
 'Andalan Perkasa Abadi Tbk.' 'Wahana Inti Makmur Tbk.'
 'Surya Permata Andalan Tbk.' 'Hassana Boga Sejahtera Tbk.'
 'Trimegah Bangun Persada Tbk.' 'Pelayaran Nelly Dwi Putri Tbk.'
 'Esta Indonesia Tbk.' 'MDTV Media Technologies Tbk.' 'NFC Indonesia Tbk.'
 'Adhi Kartiko Pratama Tbk.' 'Charnic Capital Tbk.' 'PAM Mineral Tbk.'
 'Pelat Timah Nusantara Tbk.' 'City Retail Developments Tbk.'
 'Bank OCBC NISP Tbk.' 'Bank Nationalnobu Tbk.'
 'Nusa Palapa Gemilang Tbk.' 'Nusa Raya Cipta Tbk.'
 'Nusantara Sawit Sejahtera Tbk.' 'Nusatama Berkah Tbk.'
 'Nusantara Almazia Tbk.' 'Brigit Biofarmaka Teknologi Tb'
 'OBM Drilchem Tbk.' 'Onix Capital Tbk.' 'Indo Oil Perkasa Tbk.'
 'Ancora Indonesia Resources Tbk' 'Oscar Mitra Sukses Sejahtera T'
 'Jayamas Medica Industri Tbk.' 'Indonesia Prima Property Tbk'
 'Optima Prima Metal Sinergi Tbk' 'Abadi Nusantara Hijau Investam'
 'Personel Alih Daya Tbk.' 'Minna Padi Investama Sekuritas'
 'Provident Investasi Bersama Tb' 'Bima Sakti Pertiwi Tbk.'
 'Pantai Indah Kapuk Dua Tbk.' 'Panorama Sentrawisata Tbk.'
 'Panin Sekuritas Tbk.' 'Cipta Perdana Lancar Tbk.'
 'Panca Budi Idaman Tbk.' 'Paramita Bangun Sarana Tbk.'
 'Prima Cakrawala Abadi Tbk.' 'Destinasi Tirta Nusantara Tbk'
 'Primadaya Plastisindo Tbk.' 'Panca Global Kapital Tbk.'
 'Penta Valent Tbk.' 'Pertamina Geothermal Energy Tb'
 'Tourindo Guide Indonesia Tbk.' 'Pradiksi Gunatama Tbk.'
 'Pelangi Indah Canindo Tbk' 'Multi Makmur Lemindo Tbk.'
 'Perdana Karya Perkasa Tbk' 'Planet Properindo Jaya Tbk.'
 'Plaza Indonesia Realty Tbk.' 'Putra Mandiri Jembar Tbk.'
 'Bank Pan Indonesia Tbk' 'Bank Panin Dubai Syariah Tbk.'
 'Pinago Utama Tbk.' 'Paninvest Tbk.' 'Panin Financial Tbk.'
 'Pudjiadi & Sons Tbk.' 'Pool Advista Finance Tbk.'
 'Asia Pacific Fibers Tbk' 'Nusantara Pelabuhan Handal Tbk'
 'Bliss Properti Indonesia Tbk.' 'Cikarang Listrindo Tbk.'
 'Prima Globalindo Logistik Tbk.' 'PP Presisi Tbk.'
 'Paperocks Indonesia Tbk.' 'PP Properti Tbk.'
 'Famon Awal Bros Sedaya Tbk.' 'Prodia Widyahusada Tbk.'
 'Royal Prima Tbk.' 'Prasidha Aneka Niaga Tbk' 'Palma Serasih Tbk.'
 'Red Planet Indonesia Tbk.' 'IMC Pelita Logistik Tbk.' 'Bukit Asam Tbk.'
 'Indo Straits Tbk.' 'Mitra Pack Tbk.' 'PP (Persero) Tbk.'
 'Pulau Subur Tbk.' 'Pratama Widya Tbk.' 'Petrosea Tbk.'
 'Sat Nusapersada Tbk' 'Pioneerindo Gourmet Internatio'
 'Pudjiadi Prestige Tbk.' 'Putra Rajawali Kencana Tbk.'
 'Puri Global Sukses Tbk.' 'Pakuwon Jati Tbk.' 'Pyridam Farma Tbk'
 'Sarimelati Kencana Tbk.' 'Tripar Multivision Plus Tbk.'
 'Rukun Raharja Tbk.' 'Ramayana Lestari Sentosa Tbk.'
 'Raharja Energi Cepu Tbk.' 'Ristia Bintang Mahkotasejati T'
 'Utama Radar Cahaya Tbk.' 'Roda Vivatex Tbk'
 'Repower Asia Indonesia Tbk.' 'Graha Mitra Asia Tbk.'
 'Reliance Sekuritas Indonesia T' 'Kian Santang Muliatama Tbk.'
 'Jaya Sukses Makmur Sentosa Tbk' 'RMK Energy Tbk.'
 'Royaltama Mulia Kontraktorindo' 'Pikko Land Development Tbk.'
 'Nippon Indosari Corpindo Tbk.' 'Charlie Hospital Semarang Tbk.'
 'Radiant Utama Interinsco Tbk.' 'Global Sukses Solusi Tbk.'
 'Steady Safe Tbk' 'Saptausaha Gemilangindah Tbk.'
 'Sarana Meditama Metropolitan T' 'Saraswanti Anugerah Makmur Tbk'
 'Satria Antaran Prima Tbk.' 'Kota Satu Properti Tbk.'
 'Surya Biru Murni Acetylene Tbk' 'Supreme Cable Manufacturing & '
 'Selaras Citra Nusantara Perkas' 'Organon Pharma Indonesia Tbk.'
 'Sidomulyo Selaras Tbk.' 'Millennium Pharmacon Internati'
 'Bank Woori Saudara Indonesia 1' 'Semacom Integrated Tbk.'
 'Surya Fajar Capital Tbk.' 'Sumber Global Energy Tbk.'
 'Sampoerna Agro Tbk.' 'Hotel Sahid Jaya International'
 'Sillo Maritime Perdana Tbk.' 'Sigma Energy Compressindo Tbk.'
 'Industri Jamu dan Farmasi Sido' 'Salim Ivomas Pratama Tbk.'
 'Singaraja Putra Tbk.' 'Sreeya Sewu Indonesia Tbk.' 'Sekar Laut Tbk.'
 'Superkrane Mitra Utama Tbk.' 'Gaya Abadi Sempurna Tbk.' 'Smart Tbk.'
 'Semen Baturaja Tbk.' 'Solusi Bangun Indonesia Tbk.'
 'Suryamas Dutamakmur Tbk.' 'Samudera Indonesia  Tbk.'
 'Sumber Mineral Global Abadi Tb' 'Sarana Mitra Luas Tbk.'
 'Satyamitra Kemas Lestari Tbk.' 'Sumber Mas Konstruksi Tbk.'
 'Sinergi Multi Lestarindo Tbk.' 'Golden Eagle Energy Tbk.'
 'Summarecon Agung Tbk.' 'Selamat Sempurna Tbk.'
 'Sunter Lakeside Hotel Tbk.' 'Soechi Lines Tbk.'
 'Boston Furniture Industries Tb' 'Soho Global Health Tbk.'
 'Xolare RCR Energy Tbk.' 'Sona Topas Tourism Industry Tb'
 'Shield On Service Tbk.' 'Satria Mega Kencana Tbk.' 'Suparma Tbk.'
 'Soraya Berjaya Indonesia Tbk.' 'Surya Pertiwi Tbk.'
 'Sejahteraraya Anugrahjaya Tbk.' 'Indo Acidatama Tbk'
 'Saratoga Investama Sedaya Tbk.' 'Surya Semesta Internusa Tbk.'
 'Sawit Sumbermas Sarana Tbk.' 'Sumber Tani Agung Resources Tb'
 'Lovina Beach Brewery Tbk.' 'SLJ Global Tbk.' 'Sunindo Pratama Tbk.'
 'Solusi Tunas Pratama Tbk.' 'Super Energy Tbk.'
 'Maja Agung Latexindo Tbk.' 'Saraswanti Indoland Developmen'
 'Tunas Alfin Tbk.' 'Lancartama Sejati Tbk.' 'Triputra Agro Persada Tbk.'
 'Agung Semesta Sejahtera Tbk.' 'Express Transindo Utama Tbk.'
 'Jaya Swarasa Agung Tbk.' 'Tower Bersama Infrastructure T'
 'Tunas Baru Lampung Tbk.' 'Tembaga Mulia Semanan Tbk.'
 'Mandom Indonesia Tbk.' 'Telefast Indonesia Tbk.' 'Tigaraksa Satria Tbk.'
 'Tira Austenite Tbk' 'Tirta Mahakam Resources Tbk'
 'Pabrik Kertas Tjiwi Kimia Tbk.' 'Teladan Prima Agro Tbk.' 'Temas Tbk.'
 'Tempo Intimedia Tbk.' 'Trimuda Nuansa Citra Tbk.'
 'TBS Energi Utama Tbk.' 'Rohartindo Nusantara Luas Tbk.'
 'Topindo Solusi Komunika Tbk.' 'Total Bangun Persada Tbk.'
 'Sarana Menara Nusantara Tbk.' 'Chandra Asri Pacific Tbk.'
 'Trans Power Marine Tbk.' 'Cerestar Indonesia Tbk.'
 'Trimegah Sekuritas Indonesia T' 'Perintis Triniti Properti Tbk.'
 'Trikomsel Oke Tbk.' 'Trisula International Tbk.'
 'Teknologi Karya Digital Nusa T' 'Triniti Dinamik Tbk.'
 'Tempo Scan Pacific Tbk.' 'Asuransi Tugu Pratama Indonesi'
 'King Tire Indonesia Tbk.' 'Pakuan Tbk.' 'Uni-Charm Indonesia Tbk.'
 'Agro Bahari Nusantara Tbk.' 'Damai Sejahtera Abadi Tbk.'
 'Ultrajaya Milk Industry & Trad' 'Unggul Indah Cahaya Tbk.'
 'Ulima Nitra Tbk.' 'Terang Dunia Internusa Tbk.' 'United Tractors Tbk.'
 'Unilever Indonesia Tbk.' 'Trimegah Karya Pratama Tbk.'
 'Vastland Indonesia Tbk.' 'Verona Indah Pictures Tbk.'
 'Victoria Care Indonesia Tbk.' 'Victoria Investama Tbk.'

In [59]:
main_df

,nama entitas,sektor,subsektor,currency,value currency,satuan,value satuan,auditor,ipo,jumlah saham,...,icf,fcf,laba rugi,dar,likuiditas,underwriting,kecukupan dana,premi yoy,beban klaim,retensi
kode entitas,,,,,,,,,,,,,,,,,,,,,
AALI,Astra Agro Lestari Tbk.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09 Des 1997,1.924.688.333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABBA,Mahaka Media Tbk.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03 Apr 2002,3.935.892.857,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABDA,Asuransi Bina Dana Arta Tbk.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06 Jul 1989,620.806.680,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABMM,ABM Investama Tbk.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06 Des 2011,2.753.165.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ACES,Aspirasi Hidup Indonesia Tbk.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06 Nov 2007,17.120.389.700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YULE,Yulie Sekuritas Indonesia Tbk.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 Des 2004,1.785.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZATA,Bersama Zatta Jaya Tbk.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 Nov 2022,8.496.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZINC,Kapuas Prima Coal Tbk.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16 Okt 2017,25.250.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZONE,Mega Perintis Tbk.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12 Des 2018,870.171.478,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZYRX,Zyrexindo Mandiri Buana Tbk.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 Mar 2021,1.333.334.556,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
main_df["sektor"] = gen_info["sektor"]
main_df["subsektor"] = gen_info["subsektor"]
main_df["currency"] = gen_info["mata uang pelaporan"]
main_df["satuan"] = gen_info["pembulatan yang digunakan dalam penyajian jumlah dalam laporan keuangan"]
main_df["now"] = ringkasan_saham["Penutupan"]

main_df["value currency"] = np.where(main_df["currency"].str.lower() == 'rupiah / idr', 1, 16832)

main_df["value satuan"] = np.where(main_df["satuan"].str.lower() == 'jutaan / in million', 1000000, 
                          np.where(main_df["satuan"].str.lower() == 'ribuan / in thousand', 10000, 
                                   1))







main_df

,nama entitas,sektor,subsektor,currency,value currency,satuan,value satuan,auditor,ipo,jumlah saham,...,fcf,laba rugi,dar,likuiditas,underwriting,kecukupan dana,premi yoy,beban klaim,retensi,subsketor
kode entitas,,,,,,,,,,,,,,,,,,,,,
AALI,Astra Agro Lestari Tbk.,D. Consumer Non-Cyclicals,D2. Food & Beverage,Rupiah / IDR,1,Jutaan / In Million,1000000,NaN,09 Des 1997,1.924.688.333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D2. Food & Beverage
ABBA,Mahaka Media Tbk.,E. Consumer Cyclicals,E6. Media & Entertainment,Rupiah / IDR,1,Satuan Penuh / Full Amount,1,NaN,03 Apr 2002,3.935.892.857,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E6. Media & Entertainment
ABDA,Asuransi Bina Dana Arta Tbk.,G. Financials,G4. Insurance,Rupiah / IDR,1,Ribuan / In Thousand,10000,NaN,06 Jul 1989,620.806.680,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G4. Insurance
ABMM,ABM Investama Tbk.,A. Energy,"A1. Oil, Gas & Coal",Dollar Amerika / USD,16832,Satuan Penuh / Full Amount,1,NaN,06 Des 2011,2.753.165.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"A1. Oil, Gas & Coal"
ACES,Aspirasi Hidup Indonesia Tbk.,E. Consumer Cyclicals,E7. Retailing,Rupiah / IDR,1,Satuan Penuh / Full Amount,1,NaN,06 Nov 2007,17.120.389.700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E7. Retailing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YULE,Yulie Sekuritas Indonesia Tbk.,G. Financials,G3. Investment Service,Rupiah / IDR,1,Satuan Penuh / Full Amount,1,NaN,10 Des 2004,1.785.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G3. Investment Service
ZATA,Bersama Zatta Jaya Tbk.,E. Consumer Cyclicals,E7. Retailing,Rupiah / IDR,1,Satuan Penuh / Full Amount,1,NaN,10 Nov 2022,8.496.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E7. Retailing
ZINC,Kapuas Prima Coal Tbk.,B. Basic Materials,B1. Basic Materials,Rupiah / IDR,1,Satuan Penuh / Full Amount,1,NaN,16 Okt 2017,25.250.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B1. Basic Materials
ZONE,Mega Perintis Tbk.,E. Consumer Cyclicals,E7. Retailing,Rupiah / IDR,1,Satuan Penuh / Full Amount,1,NaN,12 Des 2018,870.171.478,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E7. Retailing
ZYRX,Zyrexindo Mandiri Buana Tbk.,I. Technology,I2. Technology Hardware & Equipment,Rupiah / IDR,1,Satuan Penuh / Full Amount,1,NaN,30 Mar 2021,1.333.334.556,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I2. Technology Hardware & Equipment