In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from bs4 import BeautifulSoup
import time
import pandas as pd
import tqdm

In [ ]:
def extract_shareholder_table_with_selenium(url):
    
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--disable-gpu")
    chrome_options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36")
    
    driver = webdriver.Chrome(options=chrome_options)
    
    try:
        driver.get(url)
        time.sleep(8)
        
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        
        table = soup.find('table', {'id': 'table-shareholder'})
        
        if not table:
            raise Exception("Tabel tidak ditemukan")
        
        rows = table.find_all('tr')
        data = []
        
        for row in rows:
            cols = row.find_all(['th', 'td'])
            cols = [col.text.strip() for col in cols]
            data.append(cols)
        
        return data
    
    except Exception as e:
        print(f"Error: {e}")
        return None

In [ ]:
def shareholder_downloader ():
    hasil = {"nama entitas" : [],
             "jumlah saham" : [],
             "saham publik" : []}


    informasi = pd.read_excel("hasil/Data_Laporan_2025_TW1.xlsx", sheet_name="gen_info")
    informasi = informasi[["kode entitas", "nama entitas"]]
    informasi = informasi.apply(lambda x: x.str.lower() if x.dtype == 'object' else x)
    informasi['nama entitas'] = (
        informasi['nama entitas']
        .str.replace(r'pt|tbk|[^a-zA-Z0-9\s]', '', regex=True)  # Hapus PT/TBK dan simbol
        .str.strip()  # Hapus spasi berlebih
    )
    informasi["nama entitas"] = informasi["nama entitas"].str.replace(" ", "-")
    
    for index, row in informasi.iterrows():
        nama_entitas = row["nama entitas"]
        kode_entitas = row["kode entitas"]

        try :
            link = f"https://www.idnfinancials.com/id/{kode_entitas}/pt-{nama_entitas}-tbk"
            table_data = extract_shareholder_table_with_selenium(link)

            df = pd.DataFrame(table_data)
            df[1] = df[1].str.replace(r'\D+', '', regex=True).replace('', pd.NA).astype('Int64')
            jumlah_saham = df[1].sum()

            df = df[df[0].str.contains('Public', case=False, na=False)]
            saham_publik = df[1].sum()
            
            hasil["nama entitas"].append(nama_entitas)
            hasil["jumlah saham"].append(jumlah_saham)
            hasil["saham publik"].append(saham_publik)

            print(kode_entitas, " berhasil")

        except Exception as e:
            print(e)

    hasil = pd.DataFrame(hasil)
    return hasil

In [ ]:
hasil = shareholder_downloader()

wirg  berhasil
wmuu  berhasil
womf  berhasil
wood  berhasil
wows  berhasil
wsbp  berhasil
wskt  berhasil
wton  berhasil
yelo  berhasil
yoii  berhasil
ypas  berhasil
yule  berhasil
yupi  berhasil
zinc  berhasil
zone  berhasil
zyrx  berhasil
andi  berhasil
apex  berhasil
apii  berhasil
apli  berhasil
apln  berhasil
arci  berhasil
argo  berhasil
arii  berhasil
arka  berhasil
arko  berhasil
arna  berhasil
arto  berhasil
asbi  berhasil
asdm  berhasil
asgr  berhasil
asii  berhasil
asjt  berhasil
aslc  berhasil
asmi  berhasil
aspi  berhasil
asri  berhasil
asrm  berhasil
assa  berhasil
atap  berhasil
bhit  berhasil
bike  berhasil
bima  berhasil
bino  berhasil
bisi  berhasil
bjbr  berhasil
bksl  berhasil
omed  berhasil
pgas  berhasil
pnbn  berhasil
prda  berhasil
ranc  berhasil
Error: Tabel tidak ditemukan
1
Error: Tabel tidak ditemukan
1
sico  berhasil
smra  berhasil
spma  berhasil
tama  berhasil
tkim  berhasil
trin  berhasil
unvr  berhasil
wins  berhasil
brpt  berhasil
bsbk  berhasil
bsim  berhasil
bsml  berhasil
bssr  berhasil
bswd  berhasil
btek  berhasil
bton  berhasil
btpn  berhasil
btps  berhasil
buah  berhasil
city  berhasil
clpi  berhasil
cmnp  berhasil
cmpp  berhasil
cnko  berhasil
cnma  berhasil
coal  berhasil
prim  berhasil
psgo  berhasil
pskt  berhasil
pssi  berhasil
ptba  berhasil
ptis  berhasil
ptmp  berhasil
ptmr  berhasil
ptpp  berhasil
ptps  berhasil
ptpw  berhasil
ptro  berhasil
ptsn  berhasil
pudp  berhasil
pura  berhasil
puri  berhasil
pwon  berhasil
pzza  berhasil
raam  berhasil
raja  berhasil
drma  berhasil
dsfi  berhasil
dsng  berhasil
dvla  berhasil
dwgl  berhasil
dyan  berhasil
east  berhasil
edge  berhasil
elit  berhasil
admg  berhasil
admr  berhasil
adro  berhasil
Error: Tabel tidak ditemukan
1
Error: Tabel tidak ditemukan
1
agrs  berhasil
aisa  berhasil
akpi  berhasil
akra  berhasil
aksi  berhasil
alka  berhasil
almi  berhasil
amag  berhasil
aman  berhasil
amar  berhasil
amfg  berhasil
futr  berhasil
fwct  berhasil
gdst  berhasil
gdyr  berhasil
gema  berhasil
ggrm  berhasil
ghon  berhasil
giaa  berhasil
gjtl  berhasil
glob  berhasil
Error: Tabel tidak ditemukan
1
Error: Tabel tidak ditemukan
1
isat  berhasil
isea  berhasil
issp  berhasil
itic  berhasil
jarr  berhasil
jati  berhasil
jawa  berhasil
jecc  berhasil
jgle  berhasil
jihd  berhasil
jkon  berhasil
jksw  berhasil
gtsi  berhasil
gula  berhasil
guna  berhasil
Error: Tabel tidak ditemukan
1
hais  berhasil

In [ ]:
hasil

  nama entitas  jumlah saham  saham publik
0     wir-asia   11938622394    7281091934

In [ ]:
df = pd.DataFrame(table_data)
df[1] = df[1].str.replace(r'\D+', '', regex=True).replace('', pd.NA).astype('Int64')
sum_c = df[1].sum()

df = df[df[0].str.contains('Public', case=False, na=False)]
sum_a = df[1].sum()

print(sum_a)
print(sum_c)

854448900
8544488700

In [ ]:
informasi = pd.read_excel("hasil/Data_Laporan_2025_TW1.xlsx", sheet_name="gen_info")
informasi = informasi[["kode entitas", "nama entitas"]]
informasi = informasi.apply(lambda x: x.str.lower() if x.dtype == 'object' else x)
informasi['nama entitas'] = (
    informasi['nama entitas']
    .str.replace(r'pt|tbk|[^a-zA-Z0-9\s]', '', regex=True)  # Hapus PT/TBK dan simbol
    .str.strip()  # Hapus spasi berlebih
)
informasi["nama entitas"] = informasi["nama entitas"].str.replace(" ", "-")
informasi

    kode entitas                       nama entitas
0           wirg                           wir-asia
1           wmuu               widodo-makmur-unggas
2           womf        wahana-ottomitra-multiartha
3           wood                integra-indocabinet
4           wows                ginting-jaya-energi
..           ...                                ...
608         sdra  bank-woori-saudara-indonesia-1906
609         sema                 semacom-integrated
610         sfan                surya-fajar-capital
611         sger               sumber-global-energy
612         shid                   hotel-sahid-jaya

[613 rows x 2 columns]

In [ ]:
for index, row in informasi.iterrows():
    link = f"https://www.idnfinancials.com/id/{row["kode entitas"]}/pt-{row["nama entitas"]}-tbk"
    print(link)

https://www.idnfinancials.com/id/wirg/pt-wir-asia-tbk
https://www.idnfinancials.com/id/wmuu/pt-widodo-makmur-unggas-tbk
https://www.idnfinancials.com/id/womf/pt-wahana-ottomitra-multiartha-tbk
https://www.idnfinancials.com/id/wood/pt-integra-indocabinet-tbk
https://www.idnfinancials.com/id/wows/pt-ginting-jaya-energi-tbk
https://www.idnfinancials.com/id/wsbp/pt-waskita-beton-precast-tbk
https://www.idnfinancials.com/id/wskt/pt-waskita-karya-persero-tbk
https://www.idnfinancials.com/id/wton/pt-wijaya-karya-beton-tbk
https://www.idnfinancials.com/id/yelo/pt-yelooo-integra-datanet-tbk
https://www.idnfinancials.com/id/yoii/pt-asuransi-digital-bersama-tbk
https://www.idnfinancials.com/id/ypas/pt-yanaprima-hastapersada-tbk
https://www.idnfinancials.com/id/yule/pt-yulie-sekuritas-indonesia-tbk
https://www.idnfinancials.com/id/yupi/pt-yupi-indo-jelly-gum-tbk
https://www.idnfinancials.com/id/zinc/pt-kapuas-prima-coal-tbk
https://www.idnfinancials.com/id/zone/pt-mega-perintis-tbk
https://www.idnfinancials.com/id/zyrx/pt-zyrexindo-mandiri-buana-tbk
https://www.idnfinancials.com/id/andi/pt-andira-agro-tbk
https://www.idnfinancials.com/id/apex/pt-apexindo-pratama-duta-tbk
https://www.idnfinancials.com/id/apii/pt-arita-prima-indonesia-tbk
https://www.idnfinancials.com/id/apli/pt-asiaplast-industries-tbk
https://www.idnfinancials.com/id/apln/pt-agung-podomoro-land-tbk
https://www.idnfinancials.com/id/arci/pt-archi-indonesia-tbk
https://www.idnfinancials.com/id/argo/pt-argo-pantes-tbk
https://www.idnfinancials.com/id/arii/pt-atlas-resources-tbk
https://www.idnfinancials.com/id/arka/pt-arkha-jayanti-persada-tbk
https://www.idnfinancials.com/id/arko/pt-arkora-hydro-tbk
https://www.idnfinancials.com/id/arna/pt-arwana-citramulia-tbk
https://www.idnfinancials.com/id/arto/pt-bank-jago-tbk
https://www.idnfinancials.com/id/asbi/pt-asuransi-bintang-tbk
https://www.idnfinancials.com/id/asdm/pt-asuransi-dayin-mitra-tbk
https://www.idnfinancials.com/id/asgr/pt-astra-graphia-tbk
https://www.idnfinancials.com/id/asii/pt-astra-international-tbk
https://www.idnfinancials.com/id/asjt/pt-asuransi-jasa-tania-tbk
https://www.idnfinancials.com/id/aslc/pt-autopedia-sukses-lestari-tbk
https://www.idnfinancials.com/id/asmi/pt-asuransi-maximus-graha-persada-tbk
https://www.idnfinancials.com/id/aspi/pt-andalan-sakti-primaindo-tbk
https://www.idnfinancials.com/id/asri/pt-alam-sutera-realty-tbk
https://www.idnfinancials.com/id/asrm/pt-asuransi-ramayana-tbk
https://www.idnfinancials.com/id/assa/pt-adi-sarana-armada-tbk
https://www.idnfinancials.com/id/atap/pt-trimitra-prawara-goldland-tbk
https://www.idnfinancials.com/id/bhit/pt-mnc-asia-holding-tbk
https://www.idnfinancials.com/id/bike/pt-sepeda-bersama-indonesia-tbk
https://www.idnfinancials.com/id/bima/pt-primarindo-asia-infrastructure-tbk
https://www.idnfinancials.com/id/bino/pt-perma-plasindo-tbk
https://www.idnfinancials.com/id/bisi/pt-bisi-international-tbk
https://www.idnfinancials.com/id/bjbr/pt-bank-pembangunan-daerah-jawa-barat-dan-banten-tbk
https://www.idnfinancials.com/id/bksl/pt-sentul-city-tbk
https://www.idnfinancials.com/id/omed/pt-jayamas-medica-industri-tbk
https://www.idnfinancials.com/id/pgas/pt-perusahaan-gas-negara-tbk
https://www.idnfinancials.com/id/pnbn/pt-bank-pan-indonesia-tbk
https://www.idnfinancials.com/id/prda/pt-prodia-widyahusada-tbk
https://www.idnfinancials.com/id/ranc/pt-supra-boga-lestari-tbk
https://www.idnfinancials.com/id/rmko/pt-royaltama-mulia-kontraktorindo-tbk
https://www.idnfinancials.com/id/scco/pt-supreme-cable-manufacturing--commerce-tbk
https://www.idnfinancials.com/id/sico/pt-sigma-energy-compressindo-tbk
https://www.idnfinancials.com/id/smra/pt-summarecon-agung-tbk
https://www.idnfinancials.com/id/spma/pt-suparma-tbk
https://www.idnfinancials.com/id/tama/pt-lancartama-sejati-tbk
https://www.idnfinancials.com/id/tkim/pt-pabrik-kertas-tjiwi-kimia-tbk
https://www.idnfinancials.com/id/trin/pt-perintis-triniti-properti-tbk
https://www.idnfinancials.com/id/unvr/pt-unilever-indonesia-tbk
https://www.idnfinancials.com/id/wins/pt-wintermar-offshore-marine-tbk
https://www.idnfinancials.com/id/brpt/pt-barito-pacific-tbk
https://www.idnfinancials.com/id/bsbk/pt-wulandari-bangun-laksana-tbk
https://www.idnfinancials.com/id/bsim/pt-bank-sinarmas-tbk
https://www.idnfinancials.com/id/bsml/pt-bintang-samudera-mandiri-lines-tbk
https://www.idnfinancials.com/id/bssr/pt-baramulti-suksessarana-tbk
https://www.idnfinancials.com/id/bswd/pt-bank-of-india-indonesia-tbk
https://www.idnfinancials.com/id/btek/pt-bumi-teknokultura-unggul-tbk
https://www.idnfinancials.com/id/bton/pt-betonjaya-manunggal-tbk
https://www.idnfinancials.com/id/btpn/pt-bank-smbc-indonesia-tbk
https://www.idnfinancials.com/id/btps/pt-bank-btpn-syariah-tbk
https://www.idnfinancials.com/id/buah/pt-segar-kumala-indonesia-tbk
https://www.idnfinancials.com/id/city/pt-natura-city-developments-tbk
https://www.idnfinancials.com/id/clpi/pt-colorpak-indonesia-tbk
https://www.idnfinancials.com/id/cmnp/pt-citra-marga-nusaphala-persada-tbk
https://www.idnfinancials.com/id/cmpp/pt-airasia-indonesia-tbk
https://www.idnfinancials.com/id/cnko/pt-exploitasi-energi-indonesia-tbk
https://www.idnfinancials.com/id/cnma/pt-nusantara-sejahtera-raya-tbk
https://www.idnfinancials.com/id/coal/pt-black-diamond-resources-tbk
https://www.idnfinancials.com/id/prim/pt-royal-prima-tbk
https://www.idnfinancials.com/id/psgo/pt-palma-serasih-tbk
https://www.idnfinancials.com/id/pskt/pt-red-planet-indonesia-tbk
https://www.idnfinancials.com/id/pssi/pt-imc-pelita-logistik-tbk
https://www.idnfinancials.com/id/ptba/pt-bukit-asam-tbk
https://www.idnfinancials.com/id/ptis/pt-indo-straits-tbk
https://www.idnfinancials.com/id/ptmp/pt-mitra-pack-tbk
https://www.idnfinancials.com/id/ptmr/pt-master-print-tbk
https://www.idnfinancials.com/id/ptpp/pt-pp-persero-tbk
https://www.idnfinancials.com/id/ptps/pt-pulau-subur-tbk
https://www.idnfinancials.com/id/ptpw/pt-pratama-widya-tbk
https://www.idnfinancials.com/id/ptro/pt-petrosea-tbk
https://www.idnfinancials.com/id/ptsn/pt-sat-nusapersada-tbk
https://www.idnfinancials.com/id/pudp/pt-pudjiadi-prestige-tbk
https://www.idnfinancials.com/id/pura/pt-putra-rajawali-kencana-tbk
https://www.idnfinancials.com/id/puri/pt-puri-global-sukses-tbk
https://www.idnfinancials.com/id/pwon/pt-pakuwon-jati-tbk
https://www.idnfinancials.com/id/pzza/pt-sarimelati-kencana-tbk
https://www.idnfinancials.com/id/raam/pt-tripar-multivision-plus-tbk
https://www.idnfinancials.com/id/raja/pt-rukun-raharja-tbk
https://www.idnfinancials.com/id/drma/pt-dharma-polimetal-tbk
https://www.idnfinancials.com/id/dsfi/pt-dharma-samudera-fishing-ind-tbk
https://www.idnfinancials.com/id/dsng/pt-dharma-satya-nusantara-tbk
https://www.idnfinancials.com/id/dvla/pt-daryavaria-laboratoria-tbk
https://www.idnfinancials.com/id/dwgl/pt-dwi-guna-laksana-tbk
https://www.idnfinancials.com/id/dyan/pt-dyandra-media-international-tbk
https://www.idnfinancials.com/id/east/pt-eastparc-hotel-tbk
https://www.idnfinancials.com/id/edge/pt-indointernet-tbk
https://www.idnfinancials.com/id/elit/pt-data-sinergitama-jaya-tbk
https://www.idnfinancials.com/id/admg/pt-polychem-indonesia-tbk
https://www.idnfinancials.com/id/admr/pt-adaro-minerals-indonesia-tbk
https://www.idnfinancials.com/id/adro/pt-alamtri-resources-indonesia-tbk
https://www.idnfinancials.com/id/agar/pt-asia-sejahtera-mina-tbk
https://www.idnfinancials.com/id/agro/pt-bank-raya-indonesia-tbk
https://www.idnfinancials.com/id/agrs/pt-bank-ibk-indonesia-tbk
https://www.idnfinancials.com/id/aisa/pt-fks-food-sejahtera-tbk
https://www.idnfinancials.com/id/akpi/pt-argha-karya-prima-ind-tbk
https://www.idnfinancials.com/id/akra/pt-akr-corporindo-tbk
https://www.idnfinancials.com/id/aksi/pt-mineral-sumberdaya-mandiri-tbk
https://www.idnfinancials.com/id/alka/pt-alakasa-industrindo-tbk
https://www.idnfinancials.com/id/almi/pt-alumindo-light-metal-industry-tbk
https://www.idnfinancials.com/id/amag/pt-asuransi-multi-artha-guna-tbk
https://www.idnfinancials.com/id/aman/pt-makmur-berkah-amanda-tbk
https://www.idnfinancials.com/id/amar/pt-bank-amar-indonesia-tbk
https://www.idnfinancials.com/id/amfg/pt-asahimas-flat-glass-tbk
https://www.idnfinancials.com/id/futr/pt-futura-energi-global-tbk
https://www.idnfinancials.com/id/fwct/pt-wijaya-cahaya-timber-tbk
https://www.idnfinancials.com/id/gdst/pt-gunawan-dianjaya-steel-tbk
https://www.idnfinancials.com/id/gdyr/pt-goodyear-indonesia-tbk
https://www.idnfinancials.com/id/gema/pt-gema-grahasarana-tbk
https://www.idnfinancials.com/id/ggrm/pt-gudang-garam-tbk
https://www.idnfinancials.com/id/ghon/pt-gihon-telekomunikasi-indonesia-tbk
https://www.idnfinancials.com/id/giaa/pt-garuda-indonesia-persero-tbk
https://www.idnfinancials.com/id/gjtl/pt-gajah-tunggal-tbk
https://www.idnfinancials.com/id/glob/pt-globe-kita-terang-tbk
https://www.idnfinancials.com/id/glva/pt-galva-technologies-tbk
https://www.idnfinancials.com/id/irsx/pt-aviana-sinar-abadi-tbk
https://www.idnfinancials.com/id/isat/pt-indosat-tbk
https://www.idnfinancials.com/id/isea/pt-indo-american-seafoods-tbk
https://www.idnfinancials.com/id/issp/pt-steel-pipe-industry-of-indonesia-tbk
https://www.idnfinancials.com/id/itic/pt-indonesian-tobacco-tbk
https://www.idnfinancials.com/id/jarr/pt-jhonlin-agro-raya-tbk
https://www.idnfinancials.com/id/jati/pt-informasi-teknologi-indonesia-tbk
https://www.idnfinancials.com/id/jawa/pt-jaya-agra-wattie-tbk
https://www.idnfinancials.com/id/jecc/pt-jembo-cable-company-tbk
https://www.idnfinancials.com/id/jgle/pt-graha-andrasentra-propertindo-tbk
https://www.idnfinancials.com/id/jihd/pt-jakarta-international-hotels--development-tbk
https://www.idnfinancials.com/id/jkon/pt-jaya-konstruksi-manggala-pratama-tbk
https://www.idnfinancials.com/id/jksw/pt-jakarta-kyoei-steel-works-tbk
https://www.idnfinancials.com/id/gtsi/pt-gts-internasional-tbk
https://www.idnfinancials.com/id/gula/pt-aman-agrindo-tbk
https://www.idnfinancials.com/id/guna/pt-gunanusa-eramandiri-tbk
https://www.idnfinancials.com/id/gwsa/pt-greenwood-sejahtera-tbk
https://www.idnfinancials.com/id/hais/pt-hasnur-internasional-shipping-tbk
https://www.idnfinancials.com/id/hajj/pt-arsy-buana-travelindo-tbk
https://www.idnfinancials.com/id/halo/pt-haloni-jane-tbk
https://www.idnfinancials.com/id/hatm/pt-habco-trans-maritima-tbk
https://www.idnfinancials.com/id/hdfa/pt-radana-bhaskara-finance-tbk
https://www.idnfinancials.com/id/hdit/pt-hensel-davest-indonesia-tbk
https://www.idnfinancials.com/id/heal/pt-medikaloka-hermina-tbk
https://www.idnfinancials.com/id/heli/pt-jaya-trishindo-tbk
https://www.idnfinancials.com/id/hero/pt-dfi-retail-nusantara-tbk
https://www.idnfinancials.com/id/hmsp/pt-hm-sampoerna-tbk
https://www.idnfinancials.com/id/hoki/pt-buyung-poetra-sembada-tbk
https://www.idnfinancials.com/id/homi/pt-grand-house-mulia-tbk
https://www.idnfinancials.com/id/hope/pt-harapan-duta-pertiwi-tbk
https://www.idnfinancials.com/id/hrme/pt-menteng-heritage-realty-tbk
https://www.idnfinancials.com/id/hrta/pt-hartadinata-abadi-tbk
https://www.idnfinancials.com/id/hrum/pt-harum-energy-tbk
https://www.idnfinancials.com/id/hygn/pt-ecocare-indo-pasifik-tbk
https://www.idnfinancials.com/id/iata/pt-mnc-energy-investments-tbk
https://www.idnfinancials.com/id/ibst/pt-inti-bangun-sejahtera-tbk
https://www.idnfinancials.com/id/icbp/pt-indofood-cbp-sukses-makmur-tbk
https://www.idnfinancials.com/id/ifii/pt-indonesia-fibreboard-industry-tbk
https://www.idnfinancials.com/id/ifsh/pt-ifishdeco-tbk
https://www.idnfinancials.com/id/igar/pt-champion-pacific-indonesia-tbk
https://www.idnfinancials.com/id/iikp/pt-inti-agri-resources-tbk
https://www.idnfinancials.com/id/ikai/pt-intikeramik-alamasri-industri-tbk
https://www.idnfinancials.com/id/ikpm/pt-ikapharmindo-putramas-tbk
https://www.idnfinancials.com/id/imas/pt-indomobil-sukses-internasional-tbk
https://www.idnfinancials.com/id/impc/pt-impack-pratama-industri-tbk
https://www.idnfinancials.com/id/inai/pt-indal-aluminium-industry-tbk
https://www.idnfinancials.com/id/incf/pt-indo-komoditi-korpora-tbk
https://www.idnfinancials.com/id/indf/pt-indofood-sukses-makmur-tbk
https://www.idnfinancials.com/id/indo/pt-royalindo-investa-wijaya-tbk
https://www.idnfinancials.com/id/inds/pt-indospring-tbk
https://www.idnfinancials.com/id/indy/pt-indika-energy-tbk
https://www.idnfinancials.com/id/inet/pt-sinergi-inti-andalan-prima-tbk
https://www.idnfinancials.com/id/kdtn/pt-puri-sentul-permai-tbk
https://www.idnfinancials.com/id/keen/pt-kencana-energi-lestari-tbk
https://www.idnfinancials.com/id/ketr/pt-ketrosden-triasmitra-tbk
https://www.idnfinancials.com/id/kias/pt-keramika-indonesia-assosiasi-tbk
https://www.idnfinancials.com/id/kija/pt-kawasan-industri-jababeka-tbk
https://www.idnfinancials.com/id/kios/pt-kioson-komersial-indonesia-tbk
https://www.idnfinancials.com/id/kkes/pt-kusuma-kemindo-sentosa-tbk
https://www.idnfinancials.com/id/kkgi/pt-resource-alam-indonesia-tbk
https://www.idnfinancials.com/id/klbf/pt-kalbe-farma-tbk
https://www.idnfinancials.com/id/kmtr/pt-kirana-megatara-tbk
https://www.idnfinancials.com/id/rock/pt-rockfields-properti-indonesia-tbk
https://www.idnfinancials.com/id/roda/pt-pikko-land-development-tbk
https://www.idnfinancials.com/id/rony/pt-aesler-grup-internasional-tbk
https://www.idnfinancials.com/id/roti/pt-nippon-indosari-corpindo-tbk
https://www.idnfinancials.com/id/rsch/pt-charlie-hospital-semarang-tbk
https://www.idnfinancials.com/id/rsgk/pt-kedoya-adyaraya-tbk
https://www.idnfinancials.com/id/safe/pt-steady-safe-tbk
https://www.idnfinancials.com/id/sage/pt-saausaha-gemilangindah-tbk
https://www.idnfinancials.com/id/samf/pt-saraswanti-anugerah-makmur-tbk
https://www.idnfinancials.com/id/sapx/pt-satria-antaran-prima-tbk
https://www.idnfinancials.com/id/satu/pt-kota-satu-properti-tbk
https://www.idnfinancials.com/id/sbma/pt-surya-biru-murni-acetylene-tbk
https://www.idnfinancials.com/id/koin/pt-kokoh-inti-arebama-tbk
https://www.idnfinancials.com/id/kopi/pt-mitra-energi-persada-tbk
https://www.idnfinancials.com/id/kota/pt-dms-propertindo-tbk
https://www.idnfinancials.com/id/kpig/pt-mnc-land-tbk
https://www.idnfinancials.com/id/kras/pt-krakatau-steel-persero-tbk
https://www.idnfinancials.com/id/land/pt-trimitra-propertindo-tbk
https://www.idnfinancials.com/id/life/pt-msig-life-insurance-indonesia-tbk
https://www.idnfinancials.com/id/link/pt-link-net-tbk
https://www.idnfinancials.com/id/lmsh/pt-lionmesh-prima-tbk
https://www.idnfinancials.com/id/lpck/pt-lippo-cikarang-tbk
https://www.idnfinancials.com/id/lpli/pt-star-pacific-tbk
https://www.idnfinancials.com/id/lpps/pt-lenox-pasifik-investama-tbk
https://www.idnfinancials.com/id/lsip/pt-pp-london-sumatra-indonesia-tbk
https://www.idnfinancials.com/id/luck/pt-sentral-mitra-informatika-tbk
https://www.idnfinancials.com/id/maha/pt-mandiri-herindo-adiperkasa-tbk
https://www.idnfinancials.com/id/main/pt-malindo-feedmill-tbk
https://www.idnfinancials.com/id/mang/pt-manggung-polahraya-tbk
https://www.idnfinancials.com/id/mapa/pt-map-aktif-adiperkasa-tbk
https://www.idnfinancials.com/id/mapb/pt-map-boga-adiperkasa-tbk
https://www.idnfinancials.com/id/mapi/pt-mitra-adiperkasa-tbk
https://www.idnfinancials.com/id/maya/pt-bank-mayapada-internasional-tbk
https://www.idnfinancials.com/id/mbto/pt-martina-berto-tbk
https://www.idnfinancials.com/id/mcas/pt-m-cash-integrasi-tbk
https://www.idnfinancials.com/id/mcor/pt-bank-china-construction-bank-indonesia-tbk
https://www.idnfinancials.com/id/mdiy/pt-daya-intiguna-yasa-tbk
https://www.idnfinancials.com/id/mdki/pt-emdeki-utama-tbk
https://www.idnfinancials.com/id/mdln/pt-modernland-realty-tbk
https://www.idnfinancials.com/id/mega/pt-bank-mega-tbk
https://www.idnfinancials.com/id/meta/pt-nusantara-infrastructure-tbk
https://www.idnfinancials.com/id/mfin/pt-mandala-multifinance-tbk
https://www.idnfinancials.com/id/mfmi/pt-multifiling-mitra-indonesia-tbk
https://www.idnfinancials.com/id/mhki/pt-multi-hanna-kreasindo-tbk
https://www.idnfinancials.com/id/mice/pt-multi-indocitra-tbk
https://www.idnfinancials.com/id/mira/pt-mitra-international-resources-tbk
https://www.idnfinancials.com/id/miti/pt-mitra-investindo-tbk
https://www.idnfinancials.com/id/mkap/pt-multikarya-asia-pasifik-raya-tbk
https://www.idnfinancials.com/id/mkpi/pt-metropolitan-kentjana-tbk
https://www.idnfinancials.com/id/mktr/pt-menthobi-karyatama-raya-tbk
https://www.idnfinancials.com/id/mlia/pt-mulia-industrindo-tbk
https://www.idnfinancials.com/id/mmix/pt-multi-medika-internasional-tbk
https://www.idnfinancials.com/id/mncn/pt-media-nusantara-citra-tbk
https://www.idnfinancials.com/id/moli/pt-madusari-murni-indah-tbk
https://www.idnfinancials.com/id/mpix/pt-mitra-pedagang-indonesia-tbk
https://www.idnfinancials.com/id/mpmx/pt-mitra-pinasthika-mustika-tbk
https://www.idnfinancials.com/id/myor/pt-mayora-indah-tbk
https://www.idnfinancials.com/id/mytx/pt-asia-pacific-investama-tbk
https://www.idnfinancials.com/id/naik/pt-adiwarna-anugerah-abadi-tbk
https://www.idnfinancials.com/id/nasi/pt-wahana-inti-makmur-tbk
https://www.idnfinancials.com/id/nato/pt-surya-permata-andalan-tbk
https://www.idnfinancials.com/id/nely/pt-pelayaran-nelly-dwi-putri-tbk
https://www.idnfinancials.com/id/nice/pt-adhi-kartiko-pratama-tbk
https://www.idnfinancials.com/id/nick/pt-charnic-capital-tbk
https://www.idnfinancials.com/id/nicl/pt-pam-mineral-tbk
https://www.idnfinancials.com/id/nikl/pt-pelat-timah-nusantara-tbk
https://www.idnfinancials.com/id/nobu/pt-bank-nationalnobu-tbk
https://www.idnfinancials.com/id/npgf/pt-nusa-palapa-gemilang-tbk
https://www.idnfinancials.com/id/nrca/pt-nusa-raya-cia-tbk
https://www.idnfinancials.com/id/nsss/pt-nusantara-sawit-sejahtera-tbk
https://www.idnfinancials.com/id/ntbk/pt-nusatama-berkah-tbk
https://www.idnfinancials.com/id/nzia/pt-nusantara-almazia-tbk
https://www.idnfinancials.com/id/obat/pt-brigit-biofarmaka-teknologi-tbk
https://www.idnfinancials.com/id/ocap/pt-onix-capital-tbk
https://www.idnfinancials.com/id/oils/pt-indo-oil-perkasa-tbk
https://www.idnfinancials.com/id/okas/pt-ancora-indonesia-resources-tbk
https://www.idnfinancials.com/id/pnbs/pt-bank-panin-dubai-syariah-tbk
https://www.idnfinancials.com/id/pngo/pt-pinago-utama-tbk
https://www.idnfinancials.com/id/pnin/pt-paninvest-tbk
https://www.idnfinancials.com/id/pnlf/pt-panin-financial-tbk
https://www.idnfinancials.com/id/pola/pt-pool-advista-finance-tbk
https://www.idnfinancials.com/id/poli/pt-pollux-hotels-group-tbk
https://www.idnfinancials.com/id/poly/pt-asia-pacific-fibers-tbk
https://www.idnfinancials.com/id/port/pt-nusantara-pelabuhan-handal-tbk
https://www.idnfinancials.com/id/ppre/pt-pp-presisi-tbk
https://www.idnfinancials.com/id/admf/pt-adira-dinamika-multi-finance-tbk
https://www.idnfinancials.com/id/ammn/pt-amman-mineral-internasional-tbk
https://www.idnfinancials.com/id/asha/pt-cilacap-samudera-fishing-industry-tbk
https://www.idnfinancials.com/id/atla/pt-atlantis-subsea-indonesia-tbk
https://www.idnfinancials.com/id/bapa/pt-bekasi-asri-pemula-tbk
https://www.idnfinancials.com/id/bdkr/pt-berdikari-pondasi-perkasa-tbk
https://www.idnfinancials.com/id/bhat/pt-bhakti-multi-artha-tbk
https://www.idnfinancials.com/id/bles/pt-superior-prima-sukses-tbk
https://www.idnfinancials.com/id/bnii/pt-bank-maybank-indonesia-tbk
https://www.idnfinancials.com/id/brna/pt-berlina-tbk
https://www.idnfinancials.com/id/buka/pt-bukalapakcom-tbk
https://www.idnfinancials.com/id/cbpe/pt-citra-buana-prasida-tbk
https://www.idnfinancials.com/id/cita/pt-cita-mineral-investindo-tbk
https://www.idnfinancials.com/id/cpin/pt-charoen-pokphand-indonesia-tbk
https://www.idnfinancials.com/id/data/pt-remala-abadi-tbk
https://www.idnfinancials.com/id/digi/pt-arkadia-digital-media-tbk
https://www.idnfinancials.com/id/dpum/pt-dua-putra-utama-makmur-tbk
https://www.idnfinancials.com/id/elpi/pt-pelayaran-nasional-ekalya-purnamasari-tbk
https://www.idnfinancials.com/id/excl/pt-xl-axiata-tbk
https://www.idnfinancials.com/id/fuji/pt-fuji-finance-indonesia-tbk